In [1]:
my_list = [1,2,3]

In [1]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr


array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [16]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [17]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [21]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [23]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [39]:
arr = np.arange(25)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr = np.random.randint(0,50,10)

In [42]:
ranarr

array([41, 49, 44,  0, 47, 48,  7, 31, 26, 49])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr.max()

49

In [45]:
ranarr.min()

0

In [46]:
ranarr

array([41, 49, 44,  0, 47, 48,  7, 31, 26, 49])

In [47]:
ranarr.argmax()

1

In [48]:
ranarr.argmin()

3

In [50]:
arr = arr.reshape(5,5)

In [51]:
arr.shape

(5, 5)

In [52]:
arr.dtype

dtype('int64')

In [53]:
from numpy.random import randint

In [54]:
randint(2,10)

3

In [28]:
import numpy as np

In [29]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr_2d[2][1]

40

In [37]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [38]:
arr = np.arange(1,11)

In [39]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
bool_arr = arr > 5

In [42]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [45]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [47]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [48]:
arr[arr<3]

array([1, 2])

In [49]:
arr_2d = np.arange(50).reshape(5,10)

In [2]:
arr_2d

NameError: name 'arr_2d' is not defined

In [51]:
arr_2d[arr_2d>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])